Add database
valikaev1989/java-filmorate pull request #8
Opened 2022-07-16 14:09 UTC by valikaev1989

2022-07-17 12:51 UTC, kukolev requested changes

2022-07-17 12:51 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/models/Genre.java
> +//    public Genre(int id) {
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-07-17 12:51 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/models/Mpa.java
> +//    public Mpa(int id) {
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-07-17 12:51 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "SELECT * FROM films";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-17 12:51 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +    private static final String SELECT_ById = "SELECT * FROM GENRES WHERE GENRE_ID = ?";
Нарушение кодстайла: Название констант должны быть выполнено в верхнем регистре.

2022-07-17 12:51 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        String sql = "SELECT * FROM film_ratings WHERE rating_id = ?";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

2022-07-17 12:51 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "SELECT * FROM users";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-17 18:51 UTC, valikaev1989 commented on src/main/java/ru/yandex/practicum/filmorate/models/Genre.java
> +//    public Genre(int id) {
исправлено

2022-07-17 18:51 UTC, valikaev1989 commented on src/main/java/ru/yandex/practicum/filmorate/models/Mpa.java
> +//    public Mpa(int id) {
исправлено

2022-07-17 18:51 UTC, valikaev1989 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "SELECT * FROM films";
исправлено

2022-07-17 18:53 UTC, valikaev1989 commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +    private static final String SELECT_ById = "SELECT * FROM GENRES WHERE GENRE_ID = ?";
исправлено

2022-07-17 18:53 UTC, valikaev1989 commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        String sql = "SELECT * FROM film_ratings WHERE rating_id = ?";
исправлено

2022-07-17 18:53 UTC, valikaev1989 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "SELECT * FROM users";
исправлено

2022-07-18 07:30 UTC, kukolev requested changes

2022-07-18 07:30 UTC, kukolev commented on db/filmorate.trace.db
> +2022-07-17 17:55:01 jdbc[3]: exception
Этот файл не относится к исходному коду проекта и не нужен здесь. Файл нужно удалить.

Также нужно удалить файл filmorate.mv.db по той-же причине.

2022-07-20 14:16 UTC, closed without merging